name: CI
on: [push, pull_request]
jobs:
  deploy:
    name: "Deploy to aws"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && 'refs/head/master'
    steps:
      - name: "Configure SSH key"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/aws
          chmod 600 ~/.ssh/aws
          cat >>~/.ssh/config <<END
          Host kamuridesu.tech
            HostName kamuridesu.tech
            User admin
            IdentityFile ~/.ssh/aws
            StrictHostKeyChecking no
          END
        env:
            SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
        
      - name: "Update repository"
        run: ssh admin@kamuridesu.tech "rm -rf r34bot; git clone https://github.com/kamuridesu/r34bot.git"
      - name: "Add token"
        run: ssh admin@kamuridesu.tech 'echo "${{ secrets.TOKEN }}" > /home/admin/r34bot/tokens.json'
      - name: "Build image"
        run: ssh admin@kamuridesu.tech "cd r34bot; sudo docker build -t r34bot ."
      - name: "Deploy new version"
        run: ssh admin@kamuridesu.tech "sudo docker rm -f r34bot; sudo docker run --name r34bot -d r34bot"
